config/routes.rb
Rails.application.routes.draw do

  resources :contacts
  root to:'tops#index'

  resources :users
  resources :sessions, only: [:new,:create,:destroy]
  resources :favorites, only: [:create, :destroy]

  resources :blogs do
    collection do
      post :confirm
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

  # バリデーション
  validates :image,
    presence: true

  validates :content,
    presence: true,
    length: { in: 1..75 }

  # アソシエーション：多対多の多側
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  # アソシエーション設定一対多の多側
  belongs_to :user

  # アソシエーション設定一対多の一側
  has_many :users

  # imageカラムにImageUploaderを紐付け
  mount_uploader :image, ImageUploader

end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  # バリデーション
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence: true, length: { minimum: 6 }

  # 保存する前にメールアドレスを小文字に変換
  before_save { email.downcase! }

  # パスワードをハッシュ化
  has_secure_password

  # アソシエーション：多対多の多側
  has_many :favorites, dependent: :destroy
  has_many :favorites_blogs, through: :favorites, source: :blog

  # アソシエーション設定一対多の一側
  has_many :blogs, dependent: :destroy

  # imageカラムにImageUploaderを紐付け
  mount_uploader :image, ImageUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # 全コントローラーでSessionsHelperを使用できるようにする
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show,:edit,:update,:destroy]

  def index
    @blogs = Blog.all
  end

  def new
    if params[:back]
      @blog = Blog.new(blog_params)
      @blog.image.retrieve_from_cache! params[:cache][:image]
    else
      @blog = Blog.new
    end
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.image.retrieve_from_cache! params[:cache][:image]
    @blog.user_id = current_user.id
    if @blog.save(blog_params)
      redirect_to blogs_path,notice:"新規投稿しました！"
      @user_email = @blog.user.email
      InstaMailer.send_email(@user_email).deliver
    else
      render "new"
    end
  end

  def show
    @user_name = @blog.user.name
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  def edit
  end

  def confirm
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    render :new if @blog.invalid?
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "ブログを編集しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"ブログを削除しました！"
  end


  private
  def blog_params
    params.require(:blog).permit(:image,:content,:image_cache)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        ContactMailer.contact_mail(@contact).deliver
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :content)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(blog_id: params[:blog_id]).destroy
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    # パスワードとメールアドレスの組み合わせが有効かどうか判定
    user = User.find_by(email: params[:session][:email].downcase)

    # パスワードが一致しているかを確認
    if user && user.authenticate(params[:session][:password])
      # ログイン成功した場合
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      # ログイン失敗した場合
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit,:show,:update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render "new"
    end
  end

  def show
    session[:user_id] = @user.id
    @favorites_blogs = @user.favorites_blogs
  end

  def edit
  end

  def update
    @user.password = current_user.password_digest
    if @user.update(user_params)
      redirect_to user_path,notice: "プロフィールを更新しました！"
    else
      redirect_to user_path,notice: "プロフィールを更新できませんでした！"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name,:email,:password,
      :password_confirmation,:image,:image_cache)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true, url: choose_new_or_edit) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

        <% @blog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_new_image">
    <%= form.label :image %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="blog_new_content">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="btn blog_new_btn">
    <%= form.submit %>
  </div>

  <div class="return_index">
    <%= link_to '投稿一覧画面にもどる', blogs_path %>
  </div>

<% end %>

app/views/blogs/confirm.html.erb
<body>
  <div class="container">

    <nav class="navbar navbar-default">
      <div class="container-fluid">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
            <span class="sr-only">InstagramClone</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "InstagramClone", user_path(current_user.id), class: "navbar-brand" %>
        </div>
        <div id="gnavi" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/blogs/new">新規投稿</a></li>
            <li><a href="/blogs">投稿一覧</a></li>
            <li><%= link_to "マイページ", user_path(current_user.id) %></li>
          </ul>
        </div>

      </div>
    </nav>

    <div class="content">

      <div class="notice">
        <p></p>
      </div>

      <div class="page_title">
        <h2>以下の内容で投稿しますか？</h2>
      </div>

      <div class="main_content">
        <%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
          <%= form.hidden_field :content %>

          <div class="confirm_content">
            <div class="blog_confirm_image">
              <label>添付画像</label>
              <%= image_tag @blog.image,class:"confirm_image" %>
              <%= hidden_field_tag :"cache[image]",@blog.image.cache_name %>
            </div>
            <div class="blog_confirm_content">
              <label>投稿内容</label>
              <%= @blog.content %>
            </div>

            <div class="btn-group">
              <%= form.submit "投稿する",class:"btn btn-default" %>
            </div>
          </div><!--- End of confirm_content --->
        <% end %>

        <div class="return_blog_new">
          <%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
            <%= form.hidden_field :content %>
            <%= hidden_field_tag :"cache[image]",@blog.image.cache_name %>
            <div class="btn-group">
              <%= form.submit "もどる", name: 'back',class:"btn btn-default" %>
            </div>
          <% end %>
        </div>
      </div>

    </div> <!--End of container-->

    <footer class="footer">
      <p>Hideki Fujimoto test application</p>
    </footer>
  </div>
</body>

app/views/blogs/edit.html.erb
  <body>
    <div class="container">

      <nav class="navbar navbar-default">
        <div class="container-fluid">

          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
              <span class="sr-only">InstagramClone</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "InstagramClone", "#", class: "navbar-brand" %>
          </div>

          <div id="gnavi" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li><a href="/blogs/new">新規投稿</a></li>
              <li><a href="/blogs">投稿一覧</a></li>
              <li><a href="#">マイページ</a></li>
            </ul>
          </div>

        </div>
      </nav>

      <div class="content">

        <div class="notice">
          <p></p>
        </div>

        <div class="page_title">
          <h2>新規投稿</h2>
        </div>

        <div class="main_content">
          <%= render 'form' %>
        </div>

      </div> <!--End of container-->

      <footer class="footer">
        <p>Hideki Fujimoto test application</p>
      </footer>
    </div>
  </body>

app/views/blogs/index.html.erb
<body>
  <div class="container">

    <nav class="navbar navbar-default">
      <div class="container-fluid">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
            <span class="sr-only">InstagramClone</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "InstagramClone", user_path(current_user.id), class: "navbar-brand" %>
        </div>
        <div id="gnavi" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/blogs/new">新規投稿</a></li>
            <li><a href="/blogs">投稿一覧</a></li>
            <li><%= link_to "マイページ", user_path(current_user.id) %></li>
          </ul>
        </div>

      </div>
    </nav>

    <div class="content">

      <div class="main_content">
        <div class="page_title">
          <h3>投稿一覧</h3>
        </div>

        <div class="row">
          <table>
            <% @blogs.each do |blog| %>
              <tr class="detail_btn">
                <td><%= link_to "詳細", blog_path(blog.id) %></td>
              </tr>
              <tr class="blog_content">
                <td><%= image_tag blog.image %></td>
              </tr>
              <tr class="blog_content">
                <td><%= blog.content %></td>
              </tr>
              <% if blog.user_id == current_user.id %>
                <tr class="content_buttom">
                  <td>
                    <%= link_to "編集する", edit_blog_path(blog.id) ,class: "btn btn-default col-md-6 col-xs-12" %>
                    <%= link_to '削除する', blog_path(blog.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } ,class: "btn btn-default col-md-6 col-xs-12" %>
                  </td>
                </tr>
              <% else %>
              <% end %>
          <% end %>
        </table>
      </div>

      <div class="content-center page_btn">
        <div class="btn-group">
          <%= link_to '新しく投稿する', new_blog_path ,class: "btn btn-default" %>
        </div>
      </div>

    </div>
    </div> <!--End of content-->

    <footer class="footer">
      <p>Hideki Fujimoto test application</p>
    </footer>
  </div>
</body>

app/views/blogs/new.html.erb
<body>
  <div class="container">

    <nav class="navbar navbar-default">
      <div class="container-fluid">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
            <span class="sr-only">InstagramClone</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "InstagramClone", user_path(current_user.id), class: "navbar-brand" %>
        </div>
        <div id="gnavi" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/blogs/new">新規投稿</a></li>
            <li><a href="/blogs">投稿一覧</a></li>
            <li><%= link_to "マイページ", user_path(current_user.id) %></li>
          </ul>
        </div>

      </div>
    </nav>

      <div class="content">

        <div class="notice">
          <p><%= notice %></p>
        </div>

        <div class="blog_content">
          <div>
            <h3>新規投稿</h3>
          </div>

          <div>
            <%= render 'form' %>
          </div>
        </div>

      </div> <!--End of container-->

      <footer class="footer">
        <p>Hideki Fujimoto test application</p>
      </footer>
    </div>
  </body>

app/views/blogs/show.html.erb
<body>
  <div class="container">

    <nav class="navbar navbar-default">
      <div class="container-fluid">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
            <span class="sr-only">InstagramClone</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "InstagramClone", user_path(current_user.id), class: "navbar-brand" %>
        </div>
        <div id="gnavi" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/blogs/new">新規投稿</a></li>
            <li><a href="/blogs">投稿一覧</a></li>
            <li><%= link_to "マイページ", user_path(current_user.id) %></li>
          </ul>
        </div>

      </div>
    </nav>

    <div class="content">

      <% unless @blog.user_id.to_s == current_user.id %>
        <% if @favorite.present? %>
          <div class="confirm_content">
            <h3>以下投稿をお気に入りから解除しますか？</h3>
            <br>
            <label>image</label><br>
            <p><%= image_tag @blog.image %></p>
            <label>content</label><br>
            <p><%= @blog.content %></p>
            <label>投稿者</label><br>
            <p><%= @user_name %></p>
            <br>
            <%= link_to 'お気に入り解除する', favorite_path(blog_id: @blog.id), method: :delete, class: 'btn btn-danger confirm_btn' %>
          </div>
        <% else %>
          <div class="confirm_content">
            <h3>以下投稿をお気に入りに登録しますか？</h3>
            <br>
            <label>image</label><br>
            <p><%= image_tag @blog.image %></p>
            <label>content</label><br>
            <p><%= @blog.content %></p>
            <label>投稿者</label><br>
            <p><%= @user_name %></p>
            <br>
              <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary confirm_btn' %>
          </div>
        <% end %> <!--- End of "@favorite.present?" --->
      <% end %><!---  End of "@blog.user_id.to_s == current_user.id" --->

      <div class="return_index">
        <%= link_to '投稿一覧画面にもどる', blogs_path %>
      </div>

    </div> <!--End of content-->

<footer class="footer">
  <p>Hideki Fujimoto test application</p>
</footer>
</div>
</body>

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :contact_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :contact_email %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :contact_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.content %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Content:</strong>
  <%= @contact.content %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaClone</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="error_msg">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>
      </div>

      <div>
        <% if logged_in? %>
          <p class="text_left"><%= link_to "Profile", user_path(current_user.id) %>
          <p class="text_right"><%= link_to "Logout", session_path(current_user.id), method: :delete %>
        <% else %>
          <p class="text_left"><%= link_to "Sign up", new_user_path %>
          <p class="text_right"><%= link_to "Login", new_session_path %>
        <% end %>
      </div>

    </div>

    <%= yield %>

  </body>
</html>

app/views/tops/index.html.erb
  <body>
    <div class="container">

      <nav class="navbar navbar-default">
        <div class="container-fluid">

          <div class="navbar-header">
            <a class="navbar-brand" href="/">InstagramClone</a>
          </div>

      </nav>

      <div class="content">
        <section>
          <img src="/assets/insta_cover.jpg">
        </section>

        <section class="preamble">
          <h3>このアプリケーションについて</h3>
          <p>InstagramClone...写真でいまの状況を伝えられる...<br>
            インスタグラムを真似したテストアプリです。</p>
        </section>

        <section class="btn-group btn-group-justified" role="group">
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-default">
              <%= link_to "Sign up", new_user_path %>
            </button>
          </div>
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-default">
              <%= link_to "Login", new_session_path %>
            </button>
          </div>
        </section>

      </div> <!--End of content-->

      <footer class="footer">
        <p>Hideki Fujimoto test application</p>
      </footer>
    </div>
  </body>

app/views/users/edit.html.erb
  <body>
    <div class="container">

      <nav class="navbar navbar-default">
        <div class="container-fluid">

          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
              <span class="sr-only">InstagramClone</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "InstagramClone", user_path(current_user.id), class: "navbar-brand" %>
          </div>
          <div id="gnavi" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li><a href="/blogs/new">新規投稿</a></li>
              <li><a href="/blogs">投稿一覧</a></li>
              <li><%= link_to "マイページ", user_path(current_user.id) %></li>
            </ul>
          </div>

        </div>
      </nav>

      <div class="content">

        <div class="page_title">
          <h2>画像を編集する</h2>
        </div>

        <div class="main_content">
          <%= render 'form' %>
        </div>

      </div> <!--End of content-->

      <footer class="footer">
        <p>Hideki Fujimoto test application</p>
      </footer>
    </div>
  </body>

app/views/users/new.html.erb
<body>
  <div class="container">

    <nav class="navbar navbar-default">
      <div class="container-fluid">

        <div class="navbar-header">
          <a class="navbar-brand" href="/">InstagramClone</a>
        </div>
      </div>
    </nav>

    <div class="content">
      <div class="user_content">
      <section>
        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
            <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
      </section>

      <section class="user_new">
        <h3>新規登録</h3>
          <%= form_with(model: @user, local: true) do |f| %>
            <%= f.label :name %>
            <%= f.text_field :name %><br>
            <%= f.label :email %>
            <%= f.email_field :email %><br>
            <%= f.label :password %>
            <%= f.password_field :password %><br>
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation %><br>
            <%= f.submit "Create my account", class: "btn btn-default user_new_btn" %>
          <% end %>
      </section>
    </div>
    </div> <!--End of content-->

    <footer class="footer">
      <p>Hideki Fujimoto test application</p>
    </footer>
  </div>
</body>

app/views/users/show.html.erb
  <body>
    <div class="container">

      <nav class="navbar navbar-default">
        <div class="container-fluid">

          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
              <span class="sr-only">InstagramClone</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "InstagramClone", user_path(current_user.id), class: "navbar-brand" %>
          </div>
          <div id="gnavi" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li><a href="/blogs/new">新規投稿</a></li>
              <li><a href="/blogs">投稿一覧</a></li>
              <li><%= link_to "マイページ", user_path(current_user.id) %></li>
            </ul>
          </div>

        </div>
      </nav>

      <div class="content">

        <section class="user_profile">
          <h3><%= @user.name %>のページ</h3>
          <%= form_with(model: @user, local: true) do |form| %>
            <div class="user_profile_image">
              <%= form.label "プロフィール画像" %>
              <%= image_tag @user.image %>
              <p>↓画像を変更する
              <%= form.file_field :image %></p>
              <%= form.hidden_field :image_cache %>
            </div>
            <div class="user_profile_email">
              <label>登録メールアドレス</label>
              <%= @user.email %>
            </div>
            <div>
              <%= form.submit %>
            </div>
          <% end %>
        </section>

        <section class="user_profile">
          <h3>お気に入り投稿一覧</h3>
          <% @favorites_blogs.each do |favorites_blog| %>
            <p class="favorite_blog_image"><%= image_tag favorites_blog.image %></p>
          <% end %>
        </section>

      </div> <!--End of content-->

      <footer class="footer">
        <p>Hideki Fujimoto test application</p>
      </footer>
    </div>
  </body>